#IEC104-DATA-CONCENTRATOR
server.port=8895
#
#app config
spring.application.name=iec104-data-concentrator
spring.task.scheduling.pool.size=5
#
#Logging properties
logging.file.name=/var/log/iec104-data-concentrator/iec104-data-concentrator.log
logging.pattern.dateformat=HH:mm:ss.SSS
logging.level.root=warn
logging.level.org.hibernate.dialect.Dialect=ERROR
logging.level.bg.tid.iec104=info
logging.level.bg.tid.iec104.db.service=info
logging.level.bg.tid.iec104.service.IecHub=info
logging.level.bg.tid.iec104.service.IecScada=info
#
#IEC104 Client
iec104.identity=IEC104-DATA-CONCENTRATOR
#
#Virtual IP settings
iec104.vip.enabled=false
iec104.vip.address=192.168.56.114
iec104.vip.interface=enp0s8
#
#IEC104 Server
iec104.server.enabled=true
iec104.server.address=0.0.0.0
iec104.server.port=2406
iec104.server.maxconnections=10
iec104.server.allowedclients=
#
#Spring-Boot-Admin Settings
#basic auth creddentials
spring.security.user.name=client
spring.security.user.password=client
#configs to connect to a secured server
spring.boot.admin.client.enabled=false
spring.boot.admin.client.url=http://localhost:9191
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=smartgrid
#configs to give secured server info
spring.boot.admin.client.instance.metadata.user.name=${spring.security.user.name}
spring.boot.admin.client.instance.metadata.user.password=${spring.security.user.password}
#actuator config
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.mail.enabled=false
management.health.db.enabled=true
#
################### Hibernate Configuration ##########################
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.datasource.url= jdbc:postgresql://10.4.4.123:5432/iec104_dev
spring.datasource.username= postgres
spring.datasource.password= smartgrid
#
